services:
  - type: web
    name: jobjager-backend
    runtime: node
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false

databases:
  - name: jobjager-db
    databaseName: jobjager
    user: jobjager_user
